### ISSUE TITLE
how to play this domo?

### ISSUE THREAD

**Issue by fangjj** [zhaoyao91/react-page-cache-demo#1]
when i run this demo, i don't see nav on main.html, so change the route by myself. but i can't found the special cache work. can you show me the cache effect.

**Comment by zhaoyao91** [comment]
Yeah, this is a simple demo for test purpose, so it's really extremely simple.
you can switch pages by call `FlowRouter.go(...)` in browser console.
If you want to see some program effect, you can install react-dev-tool in chrome browser, and you can see:
![image](https://cloud.githubusercontent.com/assets/3808838/16642921/0bbd61f8-4442-11e6-802c-06423f60fab5.png)

**Comment by fangjj** [comment]
thank for your instructions. i found the cachepages. but i think enhance the demo. 
1. make the GlobalOptions.cacheTime logger,
2. make the demo complex in the suitation, like  cache listpage, detailpage.
3. which data should put in args? the rotuer query and params?
4. if args don't change, the cachepage would not render again?
can you explain to me this questions.

**Comment by zhaoyao91** [comment]
>  which data should put in args? the rotuer query and params?

generally yes, but this package doesn't stop you to save other args to page

>  if args don't change, the cachepage would not render again?

generally, your page should render by page args. if the page renders _only_ by these args, then it won't re-render without changes of args (whenever it is showing or hiding). but if it also depend on other state or data, then, it may re-render according to these changes, event if it is hiding.

I found there are more usages than I initially expected for this package. I am using it in my current project under construction, and it woks fine. so by now I don't have a plan to make this repo complex for test and time reasons.

But, if you are interested in this package and willing to make some contribution, welcome to build your own demo repo and I'd be glad to add links to you. :-)

**Comment by fangjj** [comment]
yeah, i got your mean. thank your invite me to build this package with you. I'm happy.

**Comment by zhaoyao91** [comment]
都是中国人何必客气
